apiVersion: v1
kind: Service
metadata:
  name: spotify-backend-service
spec:
  selector:
    app: spotify-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer